FROM php:8.2-fpm

COPY ./docker/php/php.ini /usr/local/etc/php/

RUN apt-get update \
  && apt-get install -y zlib1g-dev libzip-dev libc-client-dev libkrb5-dev libpq-dev \
  && apt-get install -y curl vim zip unzip \
  && pecl install xdebug \
  && docker-php-ext-install pdo_mysql \
  && docker-php-ext-enable xdebug

RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && \
    docker-php-ext-install imap

#Composer install
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

WORKDIR /var/www/src
