version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/dockerfile
    volumes:
        - ./src:/var/www/src
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lara-test
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - lara-test-db:/var/lib/mysql
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/dockerfile
    volumes:
      - ./src:/var/www/src
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  lara-test-db: